FROM openjdk:17-slim as builder

WORKDIR /app
COPY auth-service/pom.xml .
COPY auth-service/src ./src

RUN apt-get update && \
    apt-get install -y maven && \
    mvn clean package -DskipTests

FROM openjdk:17-slim
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
